### ISSUE TITLE
ionic

### ISSUE THREAD

**Issue by bnbon** [StrikeForceZero/angularjs-cordova-gulp-browserify-boilerplate#1]
Hello,

Been trying to add in ionic to this boilerplate, a few things make it tricky (I used jakes boilerplate before it moved to ES6), but there would be some advantages from ionic being a fork of this.

Ionic offers the `ionic upload` which lets you easily share and deploy to devices, and there are other nice plugins and wrappers.

I can add the ionic.project, and the io-config.json files which make it recognised as an ionic project and then it can be deployed using the ionic services, but next up I want to rip out the Cordova mentions and use ionic's wrappers.

You mentioned you would be willing to investigate an ionic fork of this, I feel it would be popular as ionic lacks a good boilerplate, as their base has all the code in single files like controllers.js.

I know you had concerns ionic was commercial, but ive no plan to use the commercial parts and my understanding is they support the efforts of ngCordova anyway.

Would you be willing to have a look into ionic replacing cordova, the ionic bundle includes angular, ngcordova etc?

Lastly;

Might be worth considering have component/module based folders rather than /controllers /services /views I think convention has now moved towards /users containing the controller and route in the folder... but thats for further down the line, and I could help more there.

---

Bit of a ramble I know!

**Comment by RLNisme** [comment]
sudo ionic platform add android

Updated the hooks directory to have execute permissions
{ [Error: ENOENT: no such file or directory, open '/home/rln/www/config.xml']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/rln/www/config.xml' }

Of course there is no directory call "/home/rln/www/config.xml" why is it looking for that but there is a config.xml file in "/home/rln/Documents/Workstation/ionic/myApp/"

**Comment by StrikeForceZero** [comment]
I'm on vacation until mid next week. 
But if you can hold until next weekend I'll see if I can get a repo with ionic support. Should be no problem.

@rlnisme I it appears it's looking for the config.xml inside the www folder instead of the root project directory

**Comment by StrikeForceZero** [comment]
I've created a repo with ionic support [here](https://github.com/StrikeForceZero/angularjs-ionic-gulp-browserify-boilerplate)

feel free to make pull requests
