### ISSUE TITLE
Upgrade asks for angular2?

### ISSUE THREAD

**Issue by Meekohi** [StrikeForceZero/angularjs-cordova-gulp-browserify-boilerplate#2]
Branched from this a few months ago and recently tried to merge the recent changes back in when the build started breaking. I know get the JS error when loading the page in the browser:

`Uncaught TypeError: _angular2.default.module is not a function`

I'm trying to understand where that is coming from? Angular2 doesn't seem like it gets mentioned anywhere, and everything just required Angular1.

**Comment by StrikeForceZero** [comment]
could you either post your package.json or push a repo that is experiencing this? 

I did remove the angular dependencies from bower and moved them back over to npm.

**Comment by Meekohi** [comment]
Yeah I noticed bower.json doesn't exist anymore so I deleted that. Private repo, but here is `package.json`. Doesn't give any indication that something other than angular1 would be used, I'm guessing it is a shim pulled in by some other dependency.

```
{
  "name": "arbf-angular",
  "version": "3.0.1",
  "author": "Michael Holroyd <meekohi@gmail.com>",
  "description": "Front-end for arbf.com",
  "contributors": [],
  "repository": {
    "type": "git",
    "url": "https://github.com/arbf/arbf-angular.git"
  },
  "keywords": [
    "express",
    "gulp",
    "browserify",
    "cordova",
    "angular",
    "sass",
    "karma",
    "jasmine",
    "protractor",
    "boilerplate"
  ],
  "private": true,
  "engines": {
    "node": ">=5.0.x"
  },
  "devDependencies": {
    "angular": "^1.5.0",
    "angular-mocks": "^1.4.2",
    "angular-ui-router": "^0.2.15",
    "ng-cordova": "^0.1.26-alpha",
    "babel-core": "^6.3.26",
    "babel-eslint": "^5.0.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-register": "^6.5.2",
    "babelify": "^7.2.0",
    "brfs": "^1.2.0",
    "browser-sync": "^2.7.6",
    "browserify": "^13.0.0",
    "browserify-istanbul": "^1.0.0",
    "browserify-ngannotate": "^2.0.0",
    "browserify-shim": "^3.8.9",
    "bulk-require": "^0.2.1",
    "bulkify": "^1.1.1",
    "cordova": "^5.4.1",
    "debowerify": "^1.3.1",
    "del": "^2.1.0",
    "fs": "0.0.2",
    "eslint": "2.2.0",
    "express": "^4.13.3",
    "gulp": "^3.9.0",
    "gulp-angular-templatecache": "^1.3.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-changed": "^1.0.0",
    "gulp-file": "^0.2.0",
    "gulp-eslint": "^2.0.0",
    "gulp-gzip": "^1.2.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.4.0",
    "gulp-jshint": "^1.8.3",
    "gulp-notify": "^2.0.0",
    "gulp-protractor": "^2.1.0",
    "gulp-rename": "^1.2.0",
    "gulp-sass": "^2.0.4",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-streamify": "^1.0.2",
    "gulp-uglify": "^1.4.2",
    "gulp-util": "^3.0.1",
    "imagemin-pngcrush": "^4.1.0",
    "isparta": "^4.0.0",
    "jshint-stylish": "^2.1.0",
    "karma": "^0.13.21",
    "karma-browserify": "^5.0.2",
    "karma-chrome-launcher": "^0.2.1",
    "karma-coverage": "douglasduteil/karma-coverage#next",
    "karma-firefox-launcher": "^0.1.3",
    "karma-jasmine": "^0.3.6",
    "karma-sauce-launcher": "^0.3.0",
    "merge-stream": "^1.0.0",
    "pretty-hrtime": "^1.0.1",
    "run-sequence": "^1.1.5",
    "tiny-lr": "^0.2.1",
    "uglifyify": "^3.0.1",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^3.7.0"
  },
  "scripts": {
    "test": "./node_modules/.bin/gulp test"
  },
  "license": "MIT"
}
```

**Comment by StrikeForceZero** [comment]
shooting in the dark but.. maybe delete the bower components and node module directory and rerun npm install

**Comment by Meekohi** [comment]
Yeah that was my thought too, but no luck.

**Comment by StrikeForceZero** [comment]
comparing the package.json only differences i see is

```
+-"node": ">=5.0.x"
+"gulp-jshint": "^1.8.3",
+"jshint-stylish": "^2.1.0",
```

which i don't think should have any affect.

I cloned a fresh copy and everything rebuilt fine (after finding and fixing an error when the user forgot to install the browser platform, Travis still passing)

I oddly remember someone having the same issue from upstream jakemmarsh/angularjs-gulp-browserify-boilerplate#144

I think I faintly recall the issue as well when I was trying to figure out how to use bower components alongside npm modules.

as a test I ran `bower install ngCordova` then `gulp dev` and sure enough I get `Uncaught TypeError: _angular2.default.module is not a function` in the browser..

but you said you removed `bower_components`.. 
so if you are absolutely sure you aren't using bower you can comment out / remove the debowerify transform. that worked for my test.

``` js
// source: ./gulp/tasks/browserify.js#65
const transforms = [
    { 'name':babelify, 'options': {}},
    //{ 'name':debowerify, 'options': {}},
    { 'name':ngAnnotate, 'options': {}},
    { 'name':'brfs', 'options': {}},
    { 'name':'bulkify', 'options': {}}
  ];
```

**Comment by Meekohi** [comment]
pfft after further exploration, I'm an idiot and hadn't actually removed `/bower_components`. After deleting that folder the error is gone. Thanks!
