### ISSUE TITLE
Heads up - using for screenshots

### ISSUE THREAD

**Issue by Naatan** [StrikeForceZero/angularjs-cordova-gulp-browserify-boilerplate#3]
Hi there, I intend to feature this project in a series of screenshots for the komodoide.com homepage, as it does a good job illustrating some of the core functionalities of Angular, Cordova and gulp.

I believe this is in line with the license, but I figured I'd give you a heads up should you have any concerns.

**Comment by StrikeForceZero** [comment]
Since the majority of this project @jakemmarsh's work it's only fair to tag him too. 

Otherwise, seems fine by me :+1:

**Comment by jakemmarsh** [comment]
Thanks for the tag @StrikeForceZero!

That's exciting though, happy to hear it can help serve that purpose. I'm okay with it

**Comment by Naatan** [comment]
Thanks guys, I didn't notice the fork when I posted this, apologies for posting it on the wrong repo. Weird that github search would show forks over original repos.

**Comment by StrikeForceZero** [comment]
Your original comment mentioned Cordova. So if you were looking for Cordova support in a nice angular boilerplate, then I think github suggested correctly. If you're omitting Cordova, then upstream is the repo you want.

**Comment by Naatan** [comment]
Fair enough :)

Fyi the screenshot is now up at http://komodoide.com/
