### ISSUE TITLE
Not serving SourceMap

### ISSUE THREAD

**Issue by Meekohi** [StrikeForceZero/angularjs-cordova-gulp-browserify-boilerplate#4]
Trying to get source map working, and not sure where to look. I can access
http://localhost:5000/js/main.js fine, but http://localhost:5000/js/main.js.map doesn't connect. Where does the server figure out which files to serve statically vs drop to angular?

**Comment by StrikeForceZero** [comment]
tracking in jakemmarsh/angularjs-gulp-browserify-boilerplate#196
