### ISSUE TITLE
ui.router

### ISSUE THREAD

**Issue by burhanfarooq** [StrikeForceZero/angularjs-cordova-gulp-browserify-boilerplate#6]
Hi,

I wanna use ui.router inside this boiler-plate, I am not sure how this will work as I am new to this angularjs area.

Can you suggest some code my hybrid app will have many views which needs to be navigation plus also used in model dialog.

please suggest, thanks.

**Comment by StrikeForceZero** [comment]
This boiler plate already uses ui.router

https://github.com/StrikeForceZero/angularjs-cordova-gulp-browserify-boilerplate/blob/master/app/js/main.js#L7

configure your routes as seen here

https://github.com/StrikeForceZero/angularjs-cordova-gulp-browserify-boilerplate/blob/master/app/js/on_config.js#L7

just inject `$state` into your controller

```js
function ExampleCtrl($state) {
    $state.go('Home'); // to navigate to the state name 'Home'
```

**Comment by burhanfarooq** [comment]
thanks
