### ISSUE TITLE
Issue injecting fingerprintauth plugin

### ISSUE THREAD

**Issue by burhanfarooq** [StrikeForceZero/angularjs-cordova-gulp-browserify-boilerplate#7]
Hi,

function ExampleCtrl(CordovaService, $cordovaDevice, $cordovaLocalNotification, $cordovaAndroidFingerprintAuth) {
  'ngInject';

above line seems not working for "$cordovaAndroidFingerprintAuth"

what I am doing wrong here? $cordovaLocalNotification is working fine but "$cordovaAndroidFingerprintAuth" 

is this some configuration i missed?

for Android
cordova plugin add cordova-plugin-android-fingerprint-auth
# Or clone the repository
cordova plugin add https://github.com/mjwheatley/cordova-plugin-android-fingerprint-auth.git

for iOS
cordova plugin add cordova-plugin-touch-id
#Or clone from the repo
cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-touch-id

**Comment by StrikeForceZero** [comment]
you are using the raw plugin, instead of using the ngCordova wrapper

see: http://ngcordova.com/docs/plugins/fingerprint/

**Comment by burhanfarooq** [comment]
Thanks yeah I was using Raw plugin.
The wrapper is working, my follow up question is can't we inject raw plugin's like the ng-cordova $cordova{{plugin name}} ?

**Comment by StrikeForceZero** [comment]
You can. But the plugins usually get added to the global window scope. so to access them I believe you'd have to do:

```javascript
function ExampleCtrl(CordovaService) {
    CordovaService.ready.then(() =>{
       window.FingerprintAuth.show(config, successCallback, errorCallbck);
    })
}
```

**Comment by burhanfarooq** [comment]
Yeah that's what I experienced in the first place after hours of trying.
Thanks for your prompt response.
